### ISSUE TITLE
Armok Vision 'Job failed to exec' for 'weird reason': 13

### ISSUE THREAD

**Issue by Simons-Mith** [JapaMala/armok-vision#49] opened 2017-05-03 23:31 UTC
I'm trying Armok Vision with DFHack 0.43.05-beta-2 on Mac OS 10.9.5

The Armok Vision app pops [up on the toolbar] for an instant [barely perceptible actually; the surrounding icons just 'jiggle'] when I try to run it, then it vanishes again.

Nothing at all in the Unity log file. In fact I've been scouring the logs to find anything at all.

Eventually I came across the following in system.log:

May  4 00:21:20 Melanie-Smith-Rawlingss-iMac com.apple.launchd.peruser.501[154] (unity.GopalGraphics.Armok Vision.303632[1464]): Job failed to exec(3) for weird reason: 13
May  4 00:21:20 Melanie-Smith-Rawlingss-iMac.local Finder[180]: 8837325: Attempting to SIGCONT to pid #1464 failed, with errno=#3, or the process failed to actually start
May  4 00:21:20 Melanie-Smith-Rawlingss-iMac.local loginwindow[42]: ERROR | -[Application setAppContext:] | Unable to get PID for context [0,290887]
May  4 00:21:20 Melanie-Smith-Rawlingss-iMac.local Dock[178]: no information back from LS about running process LSASN:{hi=0x0;lo=0x47047}
May  4 00:21:20 Melanie-Smith-Rawlingss-iMac.local Finder[180]: 8837325: Attempting to SIGCONT to pid #1464 failed, with errno=#3, or the process failed to actually start
May  4 00:21:50 --- last message repeated 98 times ---
May  4 00:22:01 Melanie-Smith-Rawlingss-iMac.local ipcserver[1470]: Valve Steam ipcserver started: 1.04

That's all I've found. At the time I had DFhack running with a fortress open, per the Armok Vision instructions. But I get the same behaviour (and the same 'weird reason' error) if I try to run Armok Vision when DFHack isn't running at all. So I'm guessing Armok Vision cannot tell there's a DF game for it to talk to??

**Comment by JapaMala** [comment] 2017-05-03 23:41
A quick Google search indicates that the permissions are messed up, which
also happens with Linux.

Try the solution here:

https://superuser.com/questions/478768/running-app-on-macosx-mountain-lion-job-failed-to-exec3-for-weird-reason-13

**Comment by lethosor** [comment] 2017-05-04 00:07
By the way, Armok Vision should at least display a window of some kind even if DF isn't running, so failure to communicate with DF wouldn't be the cause here.

I would try Japa's advice. What did you use to unzip the file you downloaded? I've seen third-party extraction tools that sometimes don't make files executable properly.

**Comment by JapaMala** [comment] 2017-05-04 00:09
It's more likely that the file is never properly made executable in the
first place, as it's built and packaged on windows, which doesn't have
those permissions.

**Comment by lethosor** [comment] 2017-05-04 00:10
At least one previous build has worked fine for me, though.

**Comment by lethosor** [comment] 2017-05-04 00:19
0.16.2 works fine for me (on OS X 10.11, using the system archive utility to extract it).

@Simons-Mith are you using 0.16.2 or an earlier version?

**Comment by Simons-Mith** [comment] 2017-05-04 00:43
I'm using 0.16.2, and I used WinZip Mac to extract it. It's the same program I've used to extract almost every zip file ever, so having it fall over on just this one application was completely unexpected. Manually chmodding the Armok Vision executable allowed it to run. WTH were Apple thinking, calling something as elementary as this a 'weird error'?? Like an idiot I believed them and assumed it was something genuinely obscure. I think Japa's explanation is the most likely, because otherwise I'd have hit it frequently. This is the first time it's come up!

**Comment by lethosor** [comment] 2017-05-04 00:46
It's executable, as far as I can tell, because Archive Utility makes it executable correctly when it's extracted. Has WinZip worked for older versions of Armok Vision?

**Comment by Simons-Mith** [comment] 2017-05-04 01:24
Well, no. I've just tried an old copy of AV 0.13.1 and that did need the same chmod tweak. However I've got quite a few other downloaded apps in Zip files - Minetest, notably, and OpenTTD, and they've been fine. Armok Vision is the first app I've ever needed to chmod.

**Comment by JapaMala** [comment] 2017-05-16 06:38
I'm honestly not sure there's a good fix for this unless I get a mac somehow, but I'll try and see if cloud builds have the same problem.

**Comment by JapaMala** [comment] 2017-05-21 16:37
https://developer.cloud.unity3d.com/share/-k5EeS8aBf/

Does this build have the same issue?

**Comment by Simons-Mith** [comment] 2017-05-23 09:14
Well, that version does run the moment I copy it out of the zip file, [although I did get a whole slew of 'Invalid pass number (6)' errors for all sorts of material types]. However, in spite of all those I can see the fortress windmill spinning, so there's no sign of the 'weird reason' error.

**Comment by JapaMala** [comment] 2017-05-23 09:14
Okay, then I'll just use the cloud build files for release, after fixing the issues.

**Comment by alexchandel** [comment] 2017-11-04 05:28
This has been fixed in all recent builds. Close?

**Comment by JapaMala** [comment] 2017-11-04 05:56
Yeah, good idea.

**Closed by JapaMala** 2017-11-04 05:56 UTC
